// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/client/accounts"
	"github.com/authclub/billforward/client/addresses"
	"github.com/authclub/billforward/client/invoices"
	"github.com/authclub/billforward/client/payment_methods"
	"github.com/authclub/billforward/client/payments"
	"github.com/authclub/billforward/client/product_rate_plans"
	"github.com/authclub/billforward/client/products"
	"github.com/authclub/billforward/client/profiles"
	"github.com/authclub/billforward/client/subscriptions"
	"github.com/authclub/billforward/client/tokenization"
	"github.com/authclub/billforward/client/webhooks"
)

// Default bill forward HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8080"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/RestAPI"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new bill forward HTTP client.
func NewHTTPClient(formats strfmt.Registry) *BillForward {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new bill forward HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *BillForward {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new bill forward client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *BillForward {
	cli := new(BillForward)
	cli.Transport = transport

	cli.Accounts = accounts.New(transport, formats)

	cli.Addresses = addresses.New(transport, formats)

	cli.Invoices = invoices.New(transport, formats)

	cli.PaymentMethods = payment_methods.New(transport, formats)

	cli.Payments = payments.New(transport, formats)

	cli.ProductRatePlans = product_rate_plans.New(transport, formats)

	cli.Products = products.New(transport, formats)

	cli.Profiles = profiles.New(transport, formats)

	cli.Subscriptions = subscriptions.New(transport, formats)

	cli.Tokenization = tokenization.New(transport, formats)

	cli.Webhooks = webhooks.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// BillForward is a client for bill forward
type BillForward struct {
	Accounts *accounts.Client

	Addresses *addresses.Client

	Invoices *invoices.Client

	PaymentMethods *payment_methods.Client

	Payments *payments.Client

	ProductRatePlans *product_rate_plans.Client

	Products *products.Client

	Profiles *profiles.Client

	Subscriptions *subscriptions.Client

	Tokenization *tokenization.Client

	Webhooks *webhooks.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *BillForward) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Accounts.SetTransport(transport)

	c.Addresses.SetTransport(transport)

	c.Invoices.SetTransport(transport)

	c.PaymentMethods.SetTransport(transport)

	c.Payments.SetTransport(transport)

	c.ProductRatePlans.SetTransport(transport)

	c.Products.SetTransport(transport)

	c.Profiles.SetTransport(transport)

	c.Subscriptions.SetTransport(transport)

	c.Tokenization.SetTransport(transport)

	c.Webhooks.SetTransport(transport)

}
