package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMetadataForProductParams creates a new GetMetadataForProductParams object
// with the default values initialized.
func NewGetMetadataForProductParams() *GetMetadataForProductParams {
	var ()
	return &GetMetadataForProductParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetadataForProductParamsWithTimeout creates a new GetMetadataForProductParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMetadataForProductParamsWithTimeout(timeout time.Duration) *GetMetadataForProductParams {
	var ()
	return &GetMetadataForProductParams{

		timeout: timeout,
	}
}

/*GetMetadataForProductParams contains all the parameters to send to the API endpoint
for the get metadata for product operation typically these are written to a http.Request
*/
type GetMetadataForProductParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*ProductID*/
	ProductID string

	timeout time.Duration
}

// WithOrganizations adds the organizations to the get metadata for product params
func (o *GetMetadataForProductParams) WithOrganizations(organizations []string) *GetMetadataForProductParams {
	o.Organizations = organizations
	return o
}

// WithProductID adds the productID to the get metadata for product params
func (o *GetMetadataForProductParams) WithProductID(productID string) *GetMetadataForProductParams {
	o.ProductID = productID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetadataForProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param product-ID
	if err := r.SetPathParam("product-ID", o.ProductID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
