package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewSetMetadataForProductParams creates a new SetMetadataForProductParams object
// with the default values initialized.
func NewSetMetadataForProductParams() *SetMetadataForProductParams {
	var ()
	return &SetMetadataForProductParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetMetadataForProductParamsWithTimeout creates a new SetMetadataForProductParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetMetadataForProductParamsWithTimeout(timeout time.Duration) *SetMetadataForProductParams {
	var ()
	return &SetMetadataForProductParams{

		timeout: timeout,
	}
}

/*SetMetadataForProductParams contains all the parameters to send to the API endpoint
for the set metadata for product operation typically these are written to a http.Request
*/
type SetMetadataForProductParams struct {

	/*Metadata*/
	Metadata models.DynamicMetadata
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*ProductID*/
	ProductID string

	timeout time.Duration
}

// WithMetadata adds the metadata to the set metadata for product params
func (o *SetMetadataForProductParams) WithMetadata(metadata models.DynamicMetadata) *SetMetadataForProductParams {
	o.Metadata = metadata
	return o
}

// WithOrganizations adds the organizations to the set metadata for product params
func (o *SetMetadataForProductParams) WithOrganizations(organizations []string) *SetMetadataForProductParams {
	o.Organizations = organizations
	return o
}

// WithProductID adds the productID to the set metadata for product params
func (o *SetMetadataForProductParams) WithProductID(productID string) *SetMetadataForProductParams {
	o.ProductID = productID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *SetMetadataForProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Metadata); err != nil {
		return err
	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param product-ID
	if err := r.SetPathParam("product-ID", o.ProductID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
