// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// CreateWebhookV2Reader is a Reader for the CreateWebhookV2 structure.
type CreateWebhookV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWebhookV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateWebhookV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateWebhookV2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateWebhookV2OK creates a CreateWebhookV2OK with default headers values
func NewCreateWebhookV2OK() *CreateWebhookV2OK {
	return &CreateWebhookV2OK{}
}

/*CreateWebhookV2OK handles this case with default header values.

success
*/
type CreateWebhookV2OK struct {
	Payload *models.WebhookPagedMetadata
}

func (o *CreateWebhookV2OK) Error() string {
	return fmt.Sprintf("[POST /webhooks/create][%d] createWebhookV2OK  %+v", 200, o.Payload)
}

func (o *CreateWebhookV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebhookPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWebhookV2Default creates a CreateWebhookV2Default with default headers values
func NewCreateWebhookV2Default(code int) *CreateWebhookV2Default {
	return &CreateWebhookV2Default{
		_statusCode: code,
	}
}

/*CreateWebhookV2Default handles this case with default header values.

error
*/
type CreateWebhookV2Default struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the create webhook v2 default response
func (o *CreateWebhookV2Default) Code() int {
	return o._statusCode
}

func (o *CreateWebhookV2Default) Error() string {
	return fmt.Sprintf("[POST /webhooks/create][%d] createWebhookV2 default  %+v", o._statusCode, o.Payload)
}

func (o *CreateWebhookV2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
