package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWebhookByIDParams creates a new GetWebhookByIDParams object
// with the default values initialized.
func NewGetWebhookByIDParams() *GetWebhookByIDParams {
	var ()
	return &GetWebhookByIDParams{}
}

/*GetWebhookByIDParams contains all the parameters to send to the API endpoint
for the get webhook by ID operation typically these are written to a http.Request
*/
type GetWebhookByIDParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*WebhookID
	  ID of the webhook.

	*/
	WebhookID string
}

// WithOrganizations adds the organizations to the get webhook by ID params
func (o *GetWebhookByIDParams) WithOrganizations(Organizations []string) *GetWebhookByIDParams {
	o.Organizations = Organizations
	return o
}

// WithWebhookID adds the webhookId to the get webhook by ID params
func (o *GetWebhookByIDParams) WithWebhookID(WebhookID string) *GetWebhookByIDParams {
	o.WebhookID = WebhookID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetWebhookByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param webhook-ID
	if err := r.SetPathParam("webhook-ID", o.WebhookID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
