package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetAllWebhooksReader is a Reader for the GetAllWebhooks structure.
type GetAllWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAllWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAllWebhooksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetAllWebhooksOK creates a GetAllWebhooksOK with default headers values
func NewGetAllWebhooksOK() *GetAllWebhooksOK {
	return &GetAllWebhooksOK{}
}

/*GetAllWebhooksOK handles this case with default header values.

success
*/
type GetAllWebhooksOK struct {
	Payload *models.WebhookPagedMetadata
}

func (o *GetAllWebhooksOK) Error() string {
	return fmt.Sprintf("[GET /webhooks][%d] getAllWebhooksOK  %+v", 200, o.Payload)
}

func (o *GetAllWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebhookPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllWebhooksDefault creates a GetAllWebhooksDefault with default headers values
func NewGetAllWebhooksDefault(code int) *GetAllWebhooksDefault {
	return &GetAllWebhooksDefault{
		_statusCode: code,
	}
}

/*GetAllWebhooksDefault handles this case with default header values.

error
*/
type GetAllWebhooksDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get all webhooks default response
func (o *GetAllWebhooksDefault) Code() int {
	return o._statusCode
}

func (o *GetAllWebhooksDefault) Error() string {
	return fmt.Sprintf("[GET /webhooks][%d] getAllWebhooks default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllWebhooksDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
