package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetWebhookByIDReader is a Reader for the GetWebhookByID structure.
type GetWebhookByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetWebhookByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWebhookByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetWebhookByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetWebhookByIDOK creates a GetWebhookByIDOK with default headers values
func NewGetWebhookByIDOK() *GetWebhookByIDOK {
	return &GetWebhookByIDOK{}
}

/*GetWebhookByIDOK handles this case with default header values.

success
*/
type GetWebhookByIDOK struct {
	Payload *models.WebhookPagedMetadata
}

func (o *GetWebhookByIDOK) Error() string {
	return fmt.Sprintf("[GET /webhooks/{webhook-ID}][%d] getWebhookByIdOK  %+v", 200, o.Payload)
}

func (o *GetWebhookByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebhookPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWebhookByIDDefault creates a GetWebhookByIDDefault with default headers values
func NewGetWebhookByIDDefault(code int) *GetWebhookByIDDefault {
	return &GetWebhookByIDDefault{
		_statusCode: code,
	}
}

/*GetWebhookByIDDefault handles this case with default header values.

error
*/
type GetWebhookByIDDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get webhook by ID default response
func (o *GetWebhookByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetWebhookByIDDefault) Error() string {
	return fmt.Sprintf("[GET /webhooks/{webhook-ID}][%d] getWebhookByID default  %+v", o._statusCode, o.Payload)
}

func (o *GetWebhookByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
