// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// RetireWebhookReader is a Reader for the RetireWebhook structure.
type RetireWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RetireWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRetireWebhookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRetireWebhookDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRetireWebhookOK creates a RetireWebhookOK with default headers values
func NewRetireWebhookOK() *RetireWebhookOK {
	return &RetireWebhookOK{}
}

/*RetireWebhookOK handles this case with default header values.

success
*/
type RetireWebhookOK struct {
	Payload *models.WebhookPagedMetadata
}

func (o *RetireWebhookOK) Error() string {
	return fmt.Sprintf("[DELETE /webhooks/{webhook-ID}][%d] retireWebhookOK  %+v", 200, o.Payload)
}

func (o *RetireWebhookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebhookPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRetireWebhookDefault creates a RetireWebhookDefault with default headers values
func NewRetireWebhookDefault(code int) *RetireWebhookDefault {
	return &RetireWebhookDefault{
		_statusCode: code,
	}
}

/*RetireWebhookDefault handles this case with default header values.

error
*/
type RetireWebhookDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the retire webhook default response
func (o *RetireWebhookDefault) Code() int {
	return o._statusCode
}

func (o *RetireWebhookDefault) Error() string {
	return fmt.Sprintf("[DELETE /webhooks/{webhook-ID}][%d] retireWebhook default  %+v", o._statusCode, o.Payload)
}

func (o *RetireWebhookDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
