package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewBatchCreateSubscriptionsParams creates a new BatchCreateSubscriptionsParams object
// with the default values initialized.
func NewBatchCreateSubscriptionsParams() *BatchCreateSubscriptionsParams {
	var ()
	return &BatchCreateSubscriptionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBatchCreateSubscriptionsParamsWithTimeout creates a new BatchCreateSubscriptionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBatchCreateSubscriptionsParamsWithTimeout(timeout time.Duration) *BatchCreateSubscriptionsParams {
	var ()
	return &BatchCreateSubscriptionsParams{

		timeout: timeout,
	}
}

/*BatchCreateSubscriptionsParams contains all the parameters to send to the API endpoint
for the batch create subscriptions operation typically these are written to a http.Request
*/
type BatchCreateSubscriptionsParams struct {

	/*Request*/
	Request *models.CreateSubscriptionBatchRequest

	timeout time.Duration
}

// WithRequest adds the request to the batch create subscriptions params
func (o *BatchCreateSubscriptionsParams) WithRequest(request *models.CreateSubscriptionBatchRequest) *BatchCreateSubscriptionsParams {
	o.Request = request
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *BatchCreateSubscriptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Request == nil {
		o.Request = new(models.CreateSubscriptionBatchRequest)
	}

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
