package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewCancelSubscriptionParams creates a new CancelSubscriptionParams object
// with the default values initialized.
func NewCancelSubscriptionParams() *CancelSubscriptionParams {
	var ()
	return &CancelSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelSubscriptionParamsWithTimeout creates a new CancelSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelSubscriptionParamsWithTimeout(timeout time.Duration) *CancelSubscriptionParams {
	var ()
	return &CancelSubscriptionParams{

		timeout: timeout,
	}
}

/*CancelSubscriptionParams contains all the parameters to send to the API endpoint
for the cancel subscription operation typically these are written to a http.Request
*/
type CancelSubscriptionParams struct {

	/*SubscriptionID*/
	SubscriptionID string
	/*SubscriptionCancellation
	  The cancellation request

	*/
	SubscriptionCancellation *models.CancelSubscriptionRequest

	timeout time.Duration
}

// WithSubscriptionID adds the subscriptionID to the cancel subscription params
func (o *CancelSubscriptionParams) WithSubscriptionID(subscriptionID string) *CancelSubscriptionParams {
	o.SubscriptionID = subscriptionID
	return o
}

// WithSubscriptionCancellation adds the subscriptionCancellation to the cancel subscription params
func (o *CancelSubscriptionParams) WithSubscriptionCancellation(subscriptionCancellation *models.CancelSubscriptionRequest) *CancelSubscriptionParams {
	o.SubscriptionCancellation = subscriptionCancellation
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CancelSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param subscription-ID
	if err := r.SetPathParam("subscription-ID", o.SubscriptionID); err != nil {
		return err
	}

	if o.SubscriptionCancellation == nil {
		o.SubscriptionCancellation = new(models.CancelSubscriptionRequest)
	}

	if err := r.SetBodyParam(o.SubscriptionCancellation); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
