package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRemovePaymentMethodFromSubscriptionParams creates a new RemovePaymentMethodFromSubscriptionParams object
// with the default values initialized.
func NewRemovePaymentMethodFromSubscriptionParams() *RemovePaymentMethodFromSubscriptionParams {
	var ()
	return &RemovePaymentMethodFromSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemovePaymentMethodFromSubscriptionParamsWithTimeout creates a new RemovePaymentMethodFromSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemovePaymentMethodFromSubscriptionParamsWithTimeout(timeout time.Duration) *RemovePaymentMethodFromSubscriptionParams {
	var ()
	return &RemovePaymentMethodFromSubscriptionParams{

		timeout: timeout,
	}
}

/*RemovePaymentMethodFromSubscriptionParams contains all the parameters to send to the API endpoint
for the remove payment method from subscription operation typically these are written to a http.Request
*/
type RemovePaymentMethodFromSubscriptionParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*PaymentMethodID*/
	PaymentMethodID string
	/*SubscriptionID*/
	SubscriptionID string

	timeout time.Duration
}

// WithOrganizations adds the organizations to the remove payment method from subscription params
func (o *RemovePaymentMethodFromSubscriptionParams) WithOrganizations(organizations []string) *RemovePaymentMethodFromSubscriptionParams {
	o.Organizations = organizations
	return o
}

// WithPaymentMethodID adds the paymentMethodID to the remove payment method from subscription params
func (o *RemovePaymentMethodFromSubscriptionParams) WithPaymentMethodID(paymentMethodID string) *RemovePaymentMethodFromSubscriptionParams {
	o.PaymentMethodID = paymentMethodID
	return o
}

// WithSubscriptionID adds the subscriptionID to the remove payment method from subscription params
func (o *RemovePaymentMethodFromSubscriptionParams) WithSubscriptionID(subscriptionID string) *RemovePaymentMethodFromSubscriptionParams {
	o.SubscriptionID = subscriptionID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *RemovePaymentMethodFromSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param payment-method-ID
	if err := r.SetPathParam("payment-method-ID", o.PaymentMethodID); err != nil {
		return err
	}

	// path param subscription-ID
	if err := r.SetPathParam("subscription-ID", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
