package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewSetMetadataForSubscriptionParams creates a new SetMetadataForSubscriptionParams object
// with the default values initialized.
func NewSetMetadataForSubscriptionParams() *SetMetadataForSubscriptionParams {
	var ()
	return &SetMetadataForSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetMetadataForSubscriptionParamsWithTimeout creates a new SetMetadataForSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetMetadataForSubscriptionParamsWithTimeout(timeout time.Duration) *SetMetadataForSubscriptionParams {
	var ()
	return &SetMetadataForSubscriptionParams{

		timeout: timeout,
	}
}

/*SetMetadataForSubscriptionParams contains all the parameters to send to the API endpoint
for the set metadata for subscription operation typically these are written to a http.Request
*/
type SetMetadataForSubscriptionParams struct {

	/*Metadata*/
	Metadata models.DynamicMetadata
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*SubscriptionID*/
	SubscriptionID string

	timeout time.Duration
}

// WithMetadata adds the metadata to the set metadata for subscription params
func (o *SetMetadataForSubscriptionParams) WithMetadata(metadata models.DynamicMetadata) *SetMetadataForSubscriptionParams {
	o.Metadata = metadata
	return o
}

// WithOrganizations adds the organizations to the set metadata for subscription params
func (o *SetMetadataForSubscriptionParams) WithOrganizations(organizations []string) *SetMetadataForSubscriptionParams {
	o.Organizations = organizations
	return o
}

// WithSubscriptionID adds the subscriptionID to the set metadata for subscription params
func (o *SetMetadataForSubscriptionParams) WithSubscriptionID(subscriptionID string) *SetMetadataForSubscriptionParams {
	o.SubscriptionID = subscriptionID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *SetMetadataForSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Metadata); err != nil {
		return err
	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param subscription-ID
	if err := r.SetPathParam("subscription-ID", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
