package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewUpsertMetadataForSubscriptionParams creates a new UpsertMetadataForSubscriptionParams object
// with the default values initialized.
func NewUpsertMetadataForSubscriptionParams() *UpsertMetadataForSubscriptionParams {
	var ()
	return &UpsertMetadataForSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpsertMetadataForSubscriptionParamsWithTimeout creates a new UpsertMetadataForSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpsertMetadataForSubscriptionParamsWithTimeout(timeout time.Duration) *UpsertMetadataForSubscriptionParams {
	var ()
	return &UpsertMetadataForSubscriptionParams{

		timeout: timeout,
	}
}

/*UpsertMetadataForSubscriptionParams contains all the parameters to send to the API endpoint
for the upsert metadata for subscription operation typically these are written to a http.Request
*/
type UpsertMetadataForSubscriptionParams struct {

	/*Metadata*/
	Metadata models.DynamicMetadata
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*SubscriptionID*/
	SubscriptionID string

	timeout time.Duration
}

// WithMetadata adds the metadata to the upsert metadata for subscription params
func (o *UpsertMetadataForSubscriptionParams) WithMetadata(metadata models.DynamicMetadata) *UpsertMetadataForSubscriptionParams {
	o.Metadata = metadata
	return o
}

// WithOrganizations adds the organizations to the upsert metadata for subscription params
func (o *UpsertMetadataForSubscriptionParams) WithOrganizations(organizations []string) *UpsertMetadataForSubscriptionParams {
	o.Organizations = organizations
	return o
}

// WithSubscriptionID adds the subscriptionID to the upsert metadata for subscription params
func (o *UpsertMetadataForSubscriptionParams) WithSubscriptionID(subscriptionID string) *UpsertMetadataForSubscriptionParams {
	o.SubscriptionID = subscriptionID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpsertMetadataForSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Metadata); err != nil {
		return err
	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param subscription-ID
	if err := r.SetPathParam("subscription-ID", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
