package product_rate_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMetadataForRatePlanParams creates a new GetMetadataForRatePlanParams object
// with the default values initialized.
func NewGetMetadataForRatePlanParams() *GetMetadataForRatePlanParams {
	var ()
	return &GetMetadataForRatePlanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetadataForRatePlanParamsWithTimeout creates a new GetMetadataForRatePlanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMetadataForRatePlanParamsWithTimeout(timeout time.Duration) *GetMetadataForRatePlanParams {
	var ()
	return &GetMetadataForRatePlanParams{

		timeout: timeout,
	}
}

/*GetMetadataForRatePlanParams contains all the parameters to send to the API endpoint
for the get metadata for rate plan operation typically these are written to a http.Request
*/
type GetMetadataForRatePlanParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*ProductRatePlanID*/
	ProductRatePlanID string

	timeout time.Duration
}

// WithOrganizations adds the organizations to the get metadata for rate plan params
func (o *GetMetadataForRatePlanParams) WithOrganizations(organizations []string) *GetMetadataForRatePlanParams {
	o.Organizations = organizations
	return o
}

// WithProductRatePlanID adds the productRatePlanID to the get metadata for rate plan params
func (o *GetMetadataForRatePlanParams) WithProductRatePlanID(productRatePlanID string) *GetMetadataForRatePlanParams {
	o.ProductRatePlanID = productRatePlanID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetadataForRatePlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param product-rate-plan-ID
	if err := r.SetPathParam("product-rate-plan-ID", o.ProductRatePlanID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
