package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewCreateAddressParams creates a new CreateAddressParams object
// with the default values initialized.
func NewCreateAddressParams() *CreateAddressParams {
	var ()
	return &CreateAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAddressParamsWithTimeout creates a new CreateAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAddressParamsWithTimeout(timeout time.Duration) *CreateAddressParams {
	var ()
	return &CreateAddressParams{

		timeout: timeout,
	}
}

/*CreateAddressParams contains all the parameters to send to the API endpoint
for the create address operation typically these are written to a http.Request
*/
type CreateAddressParams struct {

	/*Request
	  The address object to be created.

	*/
	Request *models.CreateAddressRequest

	timeout time.Duration
}

// WithRequest adds the request to the create address params
func (o *CreateAddressParams) WithRequest(request *models.CreateAddressRequest) *CreateAddressParams {
	o.Request = request
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Request == nil {
		o.Request = new(models.CreateAddressRequest)
	}

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
