package addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewUpdateAddressParams creates a new UpdateAddressParams object
// with the default values initialized.
func NewUpdateAddressParams() *UpdateAddressParams {
	var ()
	return &UpdateAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAddressParamsWithTimeout creates a new UpdateAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAddressParamsWithTimeout(timeout time.Duration) *UpdateAddressParams {
	var ()
	return &UpdateAddressParams{

		timeout: timeout,
	}
}

/*UpdateAddressParams contains all the parameters to send to the API endpoint
for the update address operation typically these are written to a http.Request
*/
type UpdateAddressParams struct {

	/*Request
	  The address object to be created.

	*/
	Request *models.UpdateAddressRequest

	timeout time.Duration
}

// WithRequest adds the request to the update address params
func (o *UpdateAddressParams) WithRequest(request *models.UpdateAddressRequest) *UpdateAddressParams {
	o.Request = request
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Request == nil {
		o.Request = new(models.UpdateAddressRequest)
	}

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
