// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPaymentByInvoiceIDParams creates a new GetPaymentByInvoiceIDParams object
// with the default values initialized.
func NewGetPaymentByInvoiceIDParams() *GetPaymentByInvoiceIDParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentByInvoiceIDParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPaymentByInvoiceIDParamsWithTimeout creates a new GetPaymentByInvoiceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPaymentByInvoiceIDParamsWithTimeout(timeout time.Duration) *GetPaymentByInvoiceIDParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentByInvoiceIDParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,

		timeout: timeout,
	}
}

// NewGetPaymentByInvoiceIDParamsWithContext creates a new GetPaymentByInvoiceIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPaymentByInvoiceIDParamsWithContext(ctx context.Context) *GetPaymentByInvoiceIDParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentByInvoiceIDParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,

		Context: ctx,
	}
}

// NewGetPaymentByInvoiceIDParamsWithHTTPClient creates a new GetPaymentByInvoiceIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPaymentByInvoiceIDParamsWithHTTPClient(client *http.Client) *GetPaymentByInvoiceIDParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentByInvoiceIDParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,
		HTTPClient:     client,
	}
}

/*GetPaymentByInvoiceIDParams contains all the parameters to send to the API endpoint
for the get payment by invoice ID operation typically these are written to a http.Request
*/
type GetPaymentByInvoiceIDParams struct {

	/*IncludeRetired
	  Whether retired products should be returned.

	*/
	IncludeRetired *bool
	/*InvoiceID
	  The string ID of the account

	*/
	InvoiceID string
	/*Offset
	  The offset from the first payment to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*Records
	  The maximum number of payments to return.

	*/
	Records *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithTimeout(timeout time.Duration) *GetPaymentByInvoiceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithContext(ctx context.Context) *GetPaymentByInvoiceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithHTTPClient(client *http.Client) *GetPaymentByInvoiceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncludeRetired adds the includeRetired to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithIncludeRetired(includeRetired *bool) *GetPaymentByInvoiceIDParams {
	o.SetIncludeRetired(includeRetired)
	return o
}

// SetIncludeRetired adds the includeRetired to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetIncludeRetired(includeRetired *bool) {
	o.IncludeRetired = includeRetired
}

// WithInvoiceID adds the invoiceID to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithInvoiceID(invoiceID string) *GetPaymentByInvoiceIDParams {
	o.SetInvoiceID(invoiceID)
	return o
}

// SetInvoiceID adds the invoiceId to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetInvoiceID(invoiceID string) {
	o.InvoiceID = invoiceID
}

// WithOffset adds the offset to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithOffset(offset *int32) *GetPaymentByInvoiceIDParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrder adds the order to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithOrder(order *string) *GetPaymentByInvoiceIDParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetOrder(order *string) {
	o.Order = order
}

// WithOrderBy adds the orderBy to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithOrderBy(orderBy *string) *GetPaymentByInvoiceIDParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrganizations adds the organizations to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithOrganizations(organizations []string) *GetPaymentByInvoiceIDParams {
	o.SetOrganizations(organizations)
	return o
}

// SetOrganizations adds the organizations to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetOrganizations(organizations []string) {
	o.Organizations = organizations
}

// WithRecords adds the records to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) WithRecords(records *int32) *GetPaymentByInvoiceIDParams {
	o.SetRecords(records)
	return o
}

// SetRecords adds the records to the get payment by invoice ID params
func (o *GetPaymentByInvoiceIDParams) SetRecords(records *int32) {
	o.Records = records
}

// WriteToRequest writes these params to a swagger request
func (o *GetPaymentByInvoiceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IncludeRetired != nil {

		// query param include_retired
		var qrIncludeRetired bool
		if o.IncludeRetired != nil {
			qrIncludeRetired = *o.IncludeRetired
		}
		qIncludeRetired := swag.FormatBool(qrIncludeRetired)
		if qIncludeRetired != "" {
			if err := r.SetQueryParam("include_retired", qIncludeRetired); err != nil {
				return err
			}
		}

	}

	// path param invoice-ID
	if err := r.SetPathParam("invoice-ID", o.InvoiceID); err != nil {
		return err
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
