package payment_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPaymentMethodByIDParams creates a new GetPaymentMethodByIDParams object
// with the default values initialized.
func NewGetPaymentMethodByIDParams() *GetPaymentMethodByIDParams {
	var ()
	return &GetPaymentMethodByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPaymentMethodByIDParamsWithTimeout creates a new GetPaymentMethodByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPaymentMethodByIDParamsWithTimeout(timeout time.Duration) *GetPaymentMethodByIDParams {
	var ()
	return &GetPaymentMethodByIDParams{

		timeout: timeout,
	}
}

/*GetPaymentMethodByIDParams contains all the parameters to send to the API endpoint
for the get payment method by ID operation typically these are written to a http.Request
*/
type GetPaymentMethodByIDParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*PaymentMethodID*/
	PaymentMethodID string

	timeout time.Duration
}

// WithOrganizations adds the organizations to the get payment method by ID params
func (o *GetPaymentMethodByIDParams) WithOrganizations(organizations []string) *GetPaymentMethodByIDParams {
	o.Organizations = organizations
	return o
}

// WithPaymentMethodID adds the paymentMethodID to the get payment method by ID params
func (o *GetPaymentMethodByIDParams) WithPaymentMethodID(paymentMethodID string) *GetPaymentMethodByIDParams {
	o.PaymentMethodID = paymentMethodID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetPaymentMethodByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param payment-method-ID
	if err := r.SetPathParam("payment-method-ID", o.PaymentMethodID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
