// Code generated by go-swagger; DO NOT EDIT.

package payment_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPaymentMethodByAccountIDParams creates a new GetPaymentMethodByAccountIDParams object
// with the default values initialized.
func NewGetPaymentMethodByAccountIDParams() *GetPaymentMethodByAccountIDParams {
	var (
		defaultOnlyDefault    = bool(false)
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentMethodByAccountIDParams{
		DefaultOnly:    &defaultOnlyDefault,
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPaymentMethodByAccountIDParamsWithTimeout creates a new GetPaymentMethodByAccountIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPaymentMethodByAccountIDParamsWithTimeout(timeout time.Duration) *GetPaymentMethodByAccountIDParams {
	var (
		defaultOnlyDefault    = bool(false)
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentMethodByAccountIDParams{
		DefaultOnly:    &defaultOnlyDefault,
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,

		timeout: timeout,
	}
}

// NewGetPaymentMethodByAccountIDParamsWithContext creates a new GetPaymentMethodByAccountIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPaymentMethodByAccountIDParamsWithContext(ctx context.Context) *GetPaymentMethodByAccountIDParams {
	var (
		defaultOnlyDefault    = bool(false)
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentMethodByAccountIDParams{
		DefaultOnly:    &defaultOnlyDefault,
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,

		Context: ctx,
	}
}

// NewGetPaymentMethodByAccountIDParamsWithHTTPClient creates a new GetPaymentMethodByAccountIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPaymentMethodByAccountIDParamsWithHTTPClient(client *http.Client) *GetPaymentMethodByAccountIDParams {
	var (
		defaultOnlyDefault    = bool(false)
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("id")
		recordsDefault        = int32(10)
	)
	return &GetPaymentMethodByAccountIDParams{
		DefaultOnly:    &defaultOnlyDefault,
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,
		HTTPClient:     client,
	}
}

/*GetPaymentMethodByAccountIDParams contains all the parameters to send to the API endpoint
for the get payment method by account ID operation typically these are written to a http.Request
*/
type GetPaymentMethodByAccountIDParams struct {

	/*AccountID*/
	AccountID string
	/*DefaultOnly
	  Whether only the defualt payment method should be returned.

	*/
	DefaultOnly *bool
	/*IncludeRetired
	  Whether retired products should be returned.

	*/
	IncludeRetired *bool
	/*Offset
	  The offset from the first payment-method to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*Records
	  The maximum number of payment-methods to return.

	*/
	Records *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithTimeout(timeout time.Duration) *GetPaymentMethodByAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithContext(ctx context.Context) *GetPaymentMethodByAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithHTTPClient(client *http.Client) *GetPaymentMethodByAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithAccountID(accountID string) *GetPaymentMethodByAccountIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithDefaultOnly adds the defaultOnly to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithDefaultOnly(defaultOnly *bool) *GetPaymentMethodByAccountIDParams {
	o.SetDefaultOnly(defaultOnly)
	return o
}

// SetDefaultOnly adds the defaultOnly to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetDefaultOnly(defaultOnly *bool) {
	o.DefaultOnly = defaultOnly
}

// WithIncludeRetired adds the includeRetired to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithIncludeRetired(includeRetired *bool) *GetPaymentMethodByAccountIDParams {
	o.SetIncludeRetired(includeRetired)
	return o
}

// SetIncludeRetired adds the includeRetired to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetIncludeRetired(includeRetired *bool) {
	o.IncludeRetired = includeRetired
}

// WithOffset adds the offset to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithOffset(offset *int32) *GetPaymentMethodByAccountIDParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrder adds the order to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithOrder(order *string) *GetPaymentMethodByAccountIDParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetOrder(order *string) {
	o.Order = order
}

// WithOrderBy adds the orderBy to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithOrderBy(orderBy *string) *GetPaymentMethodByAccountIDParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrganizations adds the organizations to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithOrganizations(organizations []string) *GetPaymentMethodByAccountIDParams {
	o.SetOrganizations(organizations)
	return o
}

// SetOrganizations adds the organizations to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetOrganizations(organizations []string) {
	o.Organizations = organizations
}

// WithRecords adds the records to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) WithRecords(records *int32) *GetPaymentMethodByAccountIDParams {
	o.SetRecords(records)
	return o
}

// SetRecords adds the records to the get payment method by account ID params
func (o *GetPaymentMethodByAccountIDParams) SetRecords(records *int32) {
	o.Records = records
}

// WriteToRequest writes these params to a swagger request
func (o *GetPaymentMethodByAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account-ID
	if err := r.SetPathParam("account-ID", o.AccountID); err != nil {
		return err
	}

	if o.DefaultOnly != nil {

		// query param default_only
		var qrDefaultOnly bool
		if o.DefaultOnly != nil {
			qrDefaultOnly = *o.DefaultOnly
		}
		qDefaultOnly := swag.FormatBool(qrDefaultOnly)
		if qDefaultOnly != "" {
			if err := r.SetQueryParam("default_only", qDefaultOnly); err != nil {
				return err
			}
		}

	}

	if o.IncludeRetired != nil {

		// query param include_retired
		var qrIncludeRetired bool
		if o.IncludeRetired != nil {
			qrIncludeRetired = *o.IncludeRetired
		}
		qIncludeRetired := swag.FormatBool(qrIncludeRetired)
		if qIncludeRetired != "" {
			if err := r.SetQueryParam("include_retired", qIncludeRetired); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
