// Code generated by go-swagger; DO NOT EDIT.

package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetProfileByAccountIDReader is a Reader for the GetProfileByAccountID structure.
type GetProfileByAccountIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProfileByAccountIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProfileByAccountIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetProfileByAccountIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProfileByAccountIDOK creates a GetProfileByAccountIDOK with default headers values
func NewGetProfileByAccountIDOK() *GetProfileByAccountIDOK {
	return &GetProfileByAccountIDOK{}
}

/*GetProfileByAccountIDOK handles this case with default header values.

success
*/
type GetProfileByAccountIDOK struct {
	Payload *models.ProfilePagedMetadata
}

func (o *GetProfileByAccountIDOK) Error() string {
	return fmt.Sprintf("[GET /profiles/account/{account-ID}][%d] getProfileByAccountIdOK  %+v", 200, o.Payload)
}

func (o *GetProfileByAccountIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProfilePagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfileByAccountIDDefault creates a GetProfileByAccountIDDefault with default headers values
func NewGetProfileByAccountIDDefault(code int) *GetProfileByAccountIDDefault {
	return &GetProfileByAccountIDDefault{
		_statusCode: code,
	}
}

/*GetProfileByAccountIDDefault handles this case with default header values.

error
*/
type GetProfileByAccountIDDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get profile by account ID default response
func (o *GetProfileByAccountIDDefault) Code() int {
	return o._statusCode
}

func (o *GetProfileByAccountIDDefault) Error() string {
	return fmt.Sprintf("[GET /profiles/account/{account-ID}][%d] getProfileByAccountID default  %+v", o._statusCode, o.Payload)
}

func (o *GetProfileByAccountIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
