package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProfileByAccountIDParams creates a new GetProfileByAccountIDParams object
// with the default values initialized.
func NewGetProfileByAccountIDParams() *GetProfileByAccountIDParams {
	var (
		offsetDefault  = int32(0)
		orderDefault   = string("DESC")
		orderByDefault = string("created")
		recordsDefault = int32(10)
	)
	return &GetProfileByAccountIDParams{
		Offset:  &offsetDefault,
		Order:   &orderDefault,
		OrderBy: &orderByDefault,
		Records: &recordsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProfileByAccountIDParamsWithTimeout creates a new GetProfileByAccountIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProfileByAccountIDParamsWithTimeout(timeout time.Duration) *GetProfileByAccountIDParams {
	var (
		offsetDefault  int32  = int32(0)
		orderDefault   string = string("DESC")
		orderByDefault string = string("created")
		recordsDefault int32  = int32(10)
	)
	return &GetProfileByAccountIDParams{
		Offset:  &offsetDefault,
		Order:   &orderDefault,
		OrderBy: &orderByDefault,
		Records: &recordsDefault,

		timeout: timeout,
	}
}

/*GetProfileByAccountIDParams contains all the parameters to send to the API endpoint
for the get profile by account ID operation typically these are written to a http.Request
*/
type GetProfileByAccountIDParams struct {

	/*AccountID
	  The account-ID of the profile.

	*/
	AccountID string
	/*Offset
	  The offset from the first profile to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organizations used to restrict the scope of API calls.

	*/
	Organizations []string
	/*Records
	  The maximum number of profiles to return.

	*/
	Records *int32

	timeout time.Duration
}

// WithAccountID adds the accountID to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithAccountID(accountID string) *GetProfileByAccountIDParams {
	o.AccountID = accountID
	return o
}

// WithOffset adds the offset to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOffset(offset *int32) *GetProfileByAccountIDParams {
	o.Offset = offset
	return o
}

// WithOrder adds the order to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOrder(order *string) *GetProfileByAccountIDParams {
	o.Order = order
	return o
}

// WithOrderBy adds the orderBy to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOrderBy(orderBy *string) *GetProfileByAccountIDParams {
	o.OrderBy = orderBy
	return o
}

// WithOrganizations adds the organizations to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOrganizations(organizations []string) *GetProfileByAccountIDParams {
	o.Organizations = organizations
	return o
}

// WithRecords adds the records to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithRecords(records *int32) *GetProfileByAccountIDParams {
	o.Records = records
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetProfileByAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param account-ID
	if err := r.SetPathParam("account-ID", o.AccountID); err != nil {
		return err
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
