// Code generated by go-swagger; DO NOT EDIT.

package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProfileByAccountIDParams creates a new GetProfileByAccountIDParams object
// with the default values initialized.
func NewGetProfileByAccountIDParams() *GetProfileByAccountIDParams {
	var (
		offsetDefault  = int32(0)
		orderDefault   = string("DESC")
		orderByDefault = string("created")
		recordsDefault = int32(10)
	)
	return &GetProfileByAccountIDParams{
		Offset:  &offsetDefault,
		Order:   &orderDefault,
		OrderBy: &orderByDefault,
		Records: &recordsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProfileByAccountIDParamsWithTimeout creates a new GetProfileByAccountIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProfileByAccountIDParamsWithTimeout(timeout time.Duration) *GetProfileByAccountIDParams {
	var (
		offsetDefault  = int32(0)
		orderDefault   = string("DESC")
		orderByDefault = string("created")
		recordsDefault = int32(10)
	)
	return &GetProfileByAccountIDParams{
		Offset:  &offsetDefault,
		Order:   &orderDefault,
		OrderBy: &orderByDefault,
		Records: &recordsDefault,

		timeout: timeout,
	}
}

// NewGetProfileByAccountIDParamsWithContext creates a new GetProfileByAccountIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProfileByAccountIDParamsWithContext(ctx context.Context) *GetProfileByAccountIDParams {
	var (
		offsetDefault  = int32(0)
		orderDefault   = string("DESC")
		orderByDefault = string("created")
		recordsDefault = int32(10)
	)
	return &GetProfileByAccountIDParams{
		Offset:  &offsetDefault,
		Order:   &orderDefault,
		OrderBy: &orderByDefault,
		Records: &recordsDefault,

		Context: ctx,
	}
}

// NewGetProfileByAccountIDParamsWithHTTPClient creates a new GetProfileByAccountIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProfileByAccountIDParamsWithHTTPClient(client *http.Client) *GetProfileByAccountIDParams {
	var (
		offsetDefault  = int32(0)
		orderDefault   = string("DESC")
		orderByDefault = string("created")
		recordsDefault = int32(10)
	)
	return &GetProfileByAccountIDParams{
		Offset:     &offsetDefault,
		Order:      &orderDefault,
		OrderBy:    &orderByDefault,
		Records:    &recordsDefault,
		HTTPClient: client,
	}
}

/*GetProfileByAccountIDParams contains all the parameters to send to the API endpoint
for the get profile by account ID operation typically these are written to a http.Request
*/
type GetProfileByAccountIDParams struct {

	/*AccountID
	  The account-ID of the profile.

	*/
	AccountID string
	/*Offset
	  The offset from the first profile to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organizations used to restrict the scope of API calls.

	*/
	Organizations []string
	/*Records
	  The maximum number of profiles to return.

	*/
	Records *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithTimeout(timeout time.Duration) *GetProfileByAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithContext(ctx context.Context) *GetProfileByAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithHTTPClient(client *http.Client) *GetProfileByAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithAccountID(accountID string) *GetProfileByAccountIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithOffset adds the offset to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOffset(offset *int32) *GetProfileByAccountIDParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrder adds the order to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOrder(order *string) *GetProfileByAccountIDParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetOrder(order *string) {
	o.Order = order
}

// WithOrderBy adds the orderBy to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOrderBy(orderBy *string) *GetProfileByAccountIDParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrganizations adds the organizations to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithOrganizations(organizations []string) *GetProfileByAccountIDParams {
	o.SetOrganizations(organizations)
	return o
}

// SetOrganizations adds the organizations to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetOrganizations(organizations []string) {
	o.Organizations = organizations
}

// WithRecords adds the records to the get profile by account ID params
func (o *GetProfileByAccountIDParams) WithRecords(records *int32) *GetProfileByAccountIDParams {
	o.SetRecords(records)
	return o
}

// SetRecords adds the records to the get profile by account ID params
func (o *GetProfileByAccountIDParams) SetRecords(records *int32) {
	o.Records = records
}

// WriteToRequest writes these params to a swagger request
func (o *GetProfileByAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account-ID
	if err := r.SetPathParam("account-ID", o.AccountID); err != nil {
		return err
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
