package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetAllProfilesReader is a Reader for the GetAllProfiles structure.
type GetAllProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAllProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAllProfilesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetAllProfilesOK creates a GetAllProfilesOK with default headers values
func NewGetAllProfilesOK() *GetAllProfilesOK {
	return &GetAllProfilesOK{}
}

/*GetAllProfilesOK handles this case with default header values.

success
*/
type GetAllProfilesOK struct {
	Payload *models.ProfilePagedMetadata
}

func (o *GetAllProfilesOK) Error() string {
	return fmt.Sprintf("[GET /profiles][%d] getAllProfilesOK  %+v", 200, o.Payload)
}

func (o *GetAllProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProfilePagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllProfilesDefault creates a GetAllProfilesDefault with default headers values
func NewGetAllProfilesDefault(code int) *GetAllProfilesDefault {
	return &GetAllProfilesDefault{
		_statusCode: code,
	}
}

/*GetAllProfilesDefault handles this case with default header values.

error
*/
type GetAllProfilesDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get all profiles default response
func (o *GetAllProfilesDefault) Code() int {
	return o._statusCode
}

func (o *GetAllProfilesDefault) Error() string {
	return fmt.Sprintf("[GET /profiles][%d] getAllProfiles default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllProfilesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
