// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllAccountsParams creates a new GetAllAccountsParams object
// with the default values initialized.
func NewGetAllAccountsParams() *GetAllAccountsParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("created")
		recordsDefault        = int32(10)
		usersOnlyDefault      = bool(false)
	)
	return &GetAllAccountsParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,
		UsersOnly:      &usersOnlyDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllAccountsParamsWithTimeout creates a new GetAllAccountsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllAccountsParamsWithTimeout(timeout time.Duration) *GetAllAccountsParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("created")
		recordsDefault        = int32(10)
		usersOnlyDefault      = bool(false)
	)
	return &GetAllAccountsParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,
		UsersOnly:      &usersOnlyDefault,

		timeout: timeout,
	}
}

// NewGetAllAccountsParamsWithContext creates a new GetAllAccountsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllAccountsParamsWithContext(ctx context.Context) *GetAllAccountsParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("created")
		recordsDefault        = int32(10)
		usersOnlyDefault      = bool(false)
	)
	return &GetAllAccountsParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,
		UsersOnly:      &usersOnlyDefault,

		Context: ctx,
	}
}

// NewGetAllAccountsParamsWithHTTPClient creates a new GetAllAccountsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllAccountsParamsWithHTTPClient(client *http.Client) *GetAllAccountsParams {
	var (
		includeRetiredDefault = bool(true)
		offsetDefault         = int32(0)
		orderDefault          = string("DESC")
		orderByDefault        = string("created")
		recordsDefault        = int32(10)
		usersOnlyDefault      = bool(false)
	)
	return &GetAllAccountsParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,
		UsersOnly:      &usersOnlyDefault,
		HTTPClient:     client,
	}
}

/*GetAllAccountsParams contains all the parameters to send to the API endpoint
for the get all accounts operation typically these are written to a http.Request
*/
type GetAllAccountsParams struct {

	/*ID
	  A list of account IDs used to filter the output.

	*/
	ID []string
	/*IncludeRetired
	  Whether retired products should be returned.

	*/
	IncludeRetired *bool
	/*Metadata*/
	Metadata *string
	/*Offset
	  The offset from the first taxation-link to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*Records
	  The maximum number of taxation-links to return.

	*/
	Records *int32
	/*UsersOnly
	  Whether only accounts have a user should be returned.

	*/
	UsersOnly *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all accounts params
func (o *GetAllAccountsParams) WithTimeout(timeout time.Duration) *GetAllAccountsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all accounts params
func (o *GetAllAccountsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all accounts params
func (o *GetAllAccountsParams) WithContext(ctx context.Context) *GetAllAccountsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all accounts params
func (o *GetAllAccountsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all accounts params
func (o *GetAllAccountsParams) WithHTTPClient(client *http.Client) *GetAllAccountsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all accounts params
func (o *GetAllAccountsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get all accounts params
func (o *GetAllAccountsParams) WithID(id []string) *GetAllAccountsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get all accounts params
func (o *GetAllAccountsParams) SetID(id []string) {
	o.ID = id
}

// WithIncludeRetired adds the includeRetired to the get all accounts params
func (o *GetAllAccountsParams) WithIncludeRetired(includeRetired *bool) *GetAllAccountsParams {
	o.SetIncludeRetired(includeRetired)
	return o
}

// SetIncludeRetired adds the includeRetired to the get all accounts params
func (o *GetAllAccountsParams) SetIncludeRetired(includeRetired *bool) {
	o.IncludeRetired = includeRetired
}

// WithMetadata adds the metadata to the get all accounts params
func (o *GetAllAccountsParams) WithMetadata(metadata *string) *GetAllAccountsParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the get all accounts params
func (o *GetAllAccountsParams) SetMetadata(metadata *string) {
	o.Metadata = metadata
}

// WithOffset adds the offset to the get all accounts params
func (o *GetAllAccountsParams) WithOffset(offset *int32) *GetAllAccountsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get all accounts params
func (o *GetAllAccountsParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrder adds the order to the get all accounts params
func (o *GetAllAccountsParams) WithOrder(order *string) *GetAllAccountsParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the get all accounts params
func (o *GetAllAccountsParams) SetOrder(order *string) {
	o.Order = order
}

// WithOrderBy adds the orderBy to the get all accounts params
func (o *GetAllAccountsParams) WithOrderBy(orderBy *string) *GetAllAccountsParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get all accounts params
func (o *GetAllAccountsParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrganizations adds the organizations to the get all accounts params
func (o *GetAllAccountsParams) WithOrganizations(organizations []string) *GetAllAccountsParams {
	o.SetOrganizations(organizations)
	return o
}

// SetOrganizations adds the organizations to the get all accounts params
func (o *GetAllAccountsParams) SetOrganizations(organizations []string) {
	o.Organizations = organizations
}

// WithRecords adds the records to the get all accounts params
func (o *GetAllAccountsParams) WithRecords(records *int32) *GetAllAccountsParams {
	o.SetRecords(records)
	return o
}

// SetRecords adds the records to the get all accounts params
func (o *GetAllAccountsParams) SetRecords(records *int32) {
	o.Records = records
}

// WithUsersOnly adds the usersOnly to the get all accounts params
func (o *GetAllAccountsParams) WithUsersOnly(usersOnly *bool) *GetAllAccountsParams {
	o.SetUsersOnly(usersOnly)
	return o
}

// SetUsersOnly adds the usersOnly to the get all accounts params
func (o *GetAllAccountsParams) SetUsersOnly(usersOnly *bool) {
	o.UsersOnly = usersOnly
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllAccountsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesID := o.ID

	joinedID := swag.JoinByFormat(valuesID, "multi")
	// query array param id
	if err := r.SetQueryParam("id", joinedID...); err != nil {
		return err
	}

	if o.IncludeRetired != nil {

		// query param include_retired
		var qrIncludeRetired bool
		if o.IncludeRetired != nil {
			qrIncludeRetired = *o.IncludeRetired
		}
		qIncludeRetired := swag.FormatBool(qrIncludeRetired)
		if qIncludeRetired != "" {
			if err := r.SetQueryParam("include_retired", qIncludeRetired); err != nil {
				return err
			}
		}

	}

	if o.Metadata != nil {

		// query param metadata
		var qrMetadata string
		if o.Metadata != nil {
			qrMetadata = *o.Metadata
		}
		qMetadata := qrMetadata
		if qMetadata != "" {
			if err := r.SetQueryParam("metadata", qMetadata); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	if o.UsersOnly != nil {

		// query param users_only
		var qrUsersOnly bool
		if o.UsersOnly != nil {
			qrUsersOnly = *o.UsersOnly
		}
		qUsersOnly := swag.FormatBool(qrUsersOnly)
		if qUsersOnly != "" {
			if err := r.SetQueryParam("users_only", qUsersOnly); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
