package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAccountByIDParams creates a new GetAccountByIDParams object
// with the default values initialized.
func NewGetAccountByIDParams() *GetAccountByIDParams {
	var ()
	return &GetAccountByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountByIDParamsWithTimeout creates a new GetAccountByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAccountByIDParamsWithTimeout(timeout time.Duration) *GetAccountByIDParams {
	var ()
	return &GetAccountByIDParams{

		timeout: timeout,
	}
}

/*GetAccountByIDParams contains all the parameters to send to the API endpoint
for the get account by ID operation typically these are written to a http.Request
*/
type GetAccountByIDParams struct {

	/*AccountID*/
	AccountID string
	/*Organizations*/
	Organizations []string

	timeout time.Duration
}

// WithAccountID adds the accountID to the get account by ID params
func (o *GetAccountByIDParams) WithAccountID(accountID string) *GetAccountByIDParams {
	o.AccountID = accountID
	return o
}

// WithOrganizations adds the organizations to the get account by ID params
func (o *GetAccountByIDParams) WithOrganizations(organizations []string) *GetAccountByIDParams {
	o.Organizations = organizations
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param account-ID
	if err := r.SetPathParam("account-ID", o.AccountID); err != nil {
		return err
	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
