package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewHaltAggregationParams creates a new HaltAggregationParams object
// with the default values initialized.
func NewHaltAggregationParams() *HaltAggregationParams {
	var ()
	return &HaltAggregationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHaltAggregationParamsWithTimeout creates a new HaltAggregationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHaltAggregationParamsWithTimeout(timeout time.Duration) *HaltAggregationParams {
	var ()
	return &HaltAggregationParams{

		timeout: timeout,
	}
}

/*HaltAggregationParams contains all the parameters to send to the API endpoint
for the halt aggregation operation typically these are written to a http.Request
*/
type HaltAggregationParams struct {

	/*AccountID*/
	AccountID string

	timeout time.Duration
}

// WithAccountID adds the accountID to the halt aggregation params
func (o *HaltAggregationParams) WithAccountID(accountID string) *HaltAggregationParams {
	o.AccountID = accountID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *HaltAggregationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param account-ID
	if err := r.SetPathParam("account-ID", o.AccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
