// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewUpsertMetadataForAccountParams creates a new UpsertMetadataForAccountParams object
// with the default values initialized.
func NewUpsertMetadataForAccountParams() *UpsertMetadataForAccountParams {
	var ()
	return &UpsertMetadataForAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpsertMetadataForAccountParamsWithTimeout creates a new UpsertMetadataForAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpsertMetadataForAccountParamsWithTimeout(timeout time.Duration) *UpsertMetadataForAccountParams {
	var ()
	return &UpsertMetadataForAccountParams{

		timeout: timeout,
	}
}

// NewUpsertMetadataForAccountParamsWithContext creates a new UpsertMetadataForAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpsertMetadataForAccountParamsWithContext(ctx context.Context) *UpsertMetadataForAccountParams {
	var ()
	return &UpsertMetadataForAccountParams{

		Context: ctx,
	}
}

// NewUpsertMetadataForAccountParamsWithHTTPClient creates a new UpsertMetadataForAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpsertMetadataForAccountParamsWithHTTPClient(client *http.Client) *UpsertMetadataForAccountParams {
	var ()
	return &UpsertMetadataForAccountParams{
		HTTPClient: client,
	}
}

/*UpsertMetadataForAccountParams contains all the parameters to send to the API endpoint
for the upsert metadata for account operation typically these are written to a http.Request
*/
type UpsertMetadataForAccountParams struct {

	/*AccountID*/
	AccountID string
	/*Metadata*/
	Metadata models.DynamicMetadata
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) WithTimeout(timeout time.Duration) *UpsertMetadataForAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) WithContext(ctx context.Context) *UpsertMetadataForAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) WithHTTPClient(client *http.Client) *UpsertMetadataForAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) WithAccountID(accountID string) *UpsertMetadataForAccountParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithMetadata adds the metadata to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) WithMetadata(metadata models.DynamicMetadata) *UpsertMetadataForAccountParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) SetMetadata(metadata models.DynamicMetadata) {
	o.Metadata = metadata
}

// WithOrganizations adds the organizations to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) WithOrganizations(organizations []string) *UpsertMetadataForAccountParams {
	o.SetOrganizations(organizations)
	return o
}

// SetOrganizations adds the organizations to the upsert metadata for account params
func (o *UpsertMetadataForAccountParams) SetOrganizations(organizations []string) {
	o.Organizations = organizations
}

// WriteToRequest writes these params to a swagger request
func (o *UpsertMetadataForAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account-ID
	if err := r.SetPathParam("account-ID", o.AccountID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Metadata); err != nil {
		return err
	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
