package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*CreateWebhookRequest create webhook request

swagger:model CreateWebhookRequest
*/
type CreateWebhookRequest struct {

	/* url
	 */
	URL string `json:"url,omitempty"`
}

// Validate validates this create webhook request
func (m *CreateWebhookRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
