// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExecuteInvoiceRequest execute invoice request
// swagger:model ExecuteInvoiceRequest
type ExecuteInvoiceRequest struct {

	// force paid
	// Required: true
	ForcePaid bool `json:"forcePaid"`
}

// Validate validates this execute invoice request
func (m *ExecuteInvoiceRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateForcePaid(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExecuteInvoiceRequest) validateForcePaid(formats strfmt.Registry) error {

	if err := validate.Required("forcePaid", "body", bool(m.ForcePaid)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExecuteInvoiceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExecuteInvoiceRequest) UnmarshalBinary(b []byte) error {
	var res ExecuteInvoiceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
