package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*ExecuteInvoiceRequest execute invoice request

swagger:model ExecuteInvoiceRequest
*/
type ExecuteInvoiceRequest struct {

	/* force paid

	Required: true
	*/
	ForcePaid bool `json:"forcePaid"`
}

// Validate validates this execute invoice request
func (m *ExecuteInvoiceRequest) Validate(formats strfmt.Registry) error {
	return nil
}
